const videos = [
    {
      "videoName": "ארוחת שישי אצל אורלי וזאביק",
      "videoSubTitle": "19.2.16",
      "videoDesc": "בני המשפחה מדברים על הכנת אוכל והתפקידים של כל אחד. בינתיים אחת הנשים מאכילה את התינוק במרק.",
      "menAndWomen": "האישה במרכז השולחן מתנשאת מעל בעלה",
      "childrenAndParents": "הגבר הצעיר מוכיח את אביו. הזוג הצעיר לא עסוק בבנם אלא הדודה היא שמאכילה אותו.",
      "year": 2016,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-30, mizrahi-16",
      "event": "friday",
      "subjects": "food-1",
      "emotions": "embarrassment-10",
      "objects": "tools-23, lights-12, art-5, comunication-11",
      "videoFileName": "ארוחת שישי אצל אורלי וזאביק 19.2.16",
      "isAutoPlay": "TRUE",
      "videoInformation": "desc-19 לפברואר, views-6, profile-Batel Erez, subscribers-31",
      "isCrop": ""
    },
    {
      "videoName": "פסח על האש אצל אביבה ויוסי",
      "videoSubTitle": "28 3 2002",
      "videoDesc": "הילדים מתנפלים על האוכל. אחת הנשים מנסה לעשות סדר.",
      "menAndWomen": "הגברים עושים בחוץ מנגל, הנשים דואגות לאוכל בפנים ולילדים.",
      "childrenAndParents": "הילדים מסתובבים חופשי בחלל.",
      "year": 2002,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-3, ashkenazi-10",
      "event": "holiday",
      "subjects": "food-28",
      "emotions": "anger-23",
      "objects": "chairs-5, tools-43, communication-1",
      "videoFileName": "פסח על האש אצל אביבה ויוסי 28 3 2002",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-8, profile-Lior Mashaal, subscribers-77",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת חג אצל משפחת רייס",
      "videoSubTitle": "אילנה אלה ואורן רוזן איתי",
      "videoDesc": "מתנהלת שיחה ואז הצלם מסב את תשומת לב הסובבים למצלמה והם משבחים את הארוחה והמארחים.",
      "menAndWomen": "הצלם צוחק ורומז שהגבר המארח לא עמל בשביל הארוחה אלא רק נשות הבית.",
      "childrenAndParents": "הילדים גדולים, אין אינטראקציה משמעותית, הם לוקחים חלק מלא בשיח סביב השולחן.",
      "year": 2012,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "mizrahi-5, ashkenazi-8",
      "event": "holiday",
      "subjects": "food-13",
      "emotions": "laugh-17",
      "objects": "tools-10",
      "videoFileName": "ארוחת חג אצל משפחת רייס אילנה אלה ואורן רוזן איתי",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-27, profile-avi rosen, subscribers-1.15K",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ראש השנה אצל ירח ואהובה",
      "videoSubTitle": "30/09/2019",
      "videoDesc": "כולם סביב השולחן, רואים אנשים לוקחים צלחות ואוכל ומספרים על האוכל. הצלם מפרשן את האירוע ומתלהב ממנו, ומדבר להוריו ברוסית בנוגע לארוחה.",
      "menAndWomen": "הגברים היו הראשונים לגשת לשולחן, הנשים המתינו בצד.",
      "childrenAndParents": "האמא מציעה לילדיה מה לאכול.",
      "year": 2019,
      "lang": "hebrew, ruski",
      "relation": 1,
      "": "",
      "foodAndDrink": "ashkenazi-18, mizrahi-3",
      "event": "holiday",
      "subjects": "food-4",
      "emotions": "happy-15, laugh-37",
      "objects": "chairs-34, tools-21, art-29",
      "videoFileName": "ארוחת ראש השנה אצל ירח ואהובה - 30_09_2019",
      "isAutoPlay": "TRUE",
      "videoInformation": "desc-אין, views-28, profile-Jazz Piano, subscribers-19",
      "isCrop": ""
    },
    {
      "videoName": "על האש אצל דייזי",
      "videoSubTitle": 1997,
      "videoDesc": "ילדה צעירה עורכת את השולחן עם אמה. ברקע דיבורים בנוגע לארוחה ולילדה. אחד הגברים מתיישב לבד על השולחן הערוך לטעום האם הדג מוכן.",
      "menAndWomen": "הגברים על המנגל, הנשים דואגות לעריכת השולחן.",
      "childrenAndParents": "הילדה יחידה מבין מבוגרים. נותנים לה לערוך את השולחן, מדברים א/עליה בנוכחותה כמעט ללא מענה או תגובה ממנה.",
      "year": 1997,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "ashkenazi-17, bread-33, mizrahi-50",
      "event": "bbq",
      "subjects": "food-18, politiks-20",
      "emotions": "calm-28, anger-40",
      "objects": "chairs-2, tools-6",
      "videoFileName": "על האש אצל דייזי 1997",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-310, profile-ronnydvr172, subscribers-568",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת בוקר אצל אופירה",
      "videoSubTitle": "פסח 13.",
      "videoDesc": "האנשים מדברים על האוכל והצלמת מסבה את תשומת הלב של הסובבים לאירוח המפנק. שמחים על פתיחת עונת הקיץ.",
      "menAndWomen": "הנשים מפרגנות ברצינות, אחד הגברים מסיים את דבריו במעט ציניות. הצלמת מעמידה אותו במקום.",
      "childrenAndParents": "הילדים יושבים בנפרד אחד מהשניה, הילד הקטן בטיפולה של האמא והילדה הגדולה יושבת ואוכלת ללא דאגה.",
      "year": 2013,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "ashkenazi-12",
      "event": "holiday",
      "subjects": "memory-15, food-12",
      "emotions": "happy-10, embarrassment-26",
      "objects": "tools-4",
      "videoFileName": "פסח 13.ארוחת בוקר אצל אופירה",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-132, profile-Dorit Talor, subscribers-12",
      "isCrop": "FALSE"
    },
    {
      "videoName": "ארוחת חג הפסח אצל דפנה ואיל",
      "videoSubTitle": "",
      "videoDesc": "חלק מסובבי השולחן שרים שיר מהגדת הפסח, הצעירים בקצה החדר מצחקקים.",
      "menAndWomen": "הגברים והנשים יושבים באופן מעורב בשולחן.",
      "childrenAndParents": "הילדים גדולים ויושבים בחלק אחד של השולחן מהוריהם. לא נראה יחס מסוים בין ההורים וילדיהם.",
      "year": 2011,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "alcohol-4",
      "event": "holiday",
      "subjects": "text-0",
      "emotions": "happy-16",
      "objects": "art-13",
      "videoFileName": "ארוחת חג הפסח אצל דפנה ואיל",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-246, profile-merkelchaim, subscribers-1",
      "isCrop": ""
    },
    {
      "videoName": "על האש אצל דני ומירה",
      "videoSubTitle": "בחולון 1988",
      "videoDesc": "הצלם מצלם שיחה שלו עם מישהו ואז את הסובבים. הסבא עושה מנגל והסבתא מתקשה להוציא את האוכל לילדים.",
      "menAndWomen": "2 גברים על המנגל, אישה מתעסקת עם הילדים.",
      "childrenAndParents": "נראה כי ההורים לא עם הילדים שלהם והסבתא היא שמטפלת בהם.",
      "year": 1988,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-16",
      "event": "bbq",
      "subjects": "food-22",
      "emotions": "laugh-13",
      "objects": "chairs-6",
      "videoFileName": "על האש אצל דני ומירה בחולון 1988",
      "isAutoPlay": "",
      "videoInformation": "desc-אורחים: רותי, מנחם ודגל, מאיר ולבנה\nחלי,שגיא ורועי, views-15, profile-צבי דר, subscribers-9",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת חג פסח אצלנו",
      "videoSubTitle": "07/04/12",
      "videoDesc": "כולם יושבים מסביב לשולחן ועסוקים באוכל.",
      "menAndWomen": "אין",
      "childrenAndParents": "אחד הילדים נעזר באמו, היא מעמידה אותו במקום.",
      "year": 2012,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "mizrahi-8",
      "event": "holiday",
      "subjects": "food-0",
      "emotions": "",
      "objects": "chairs-10, communication-2",
      "videoFileName": "ארוחת חג פסח אצלנו 070412",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-42, profile-udi Laba, subscribers-17",
      "isCrop": "FALSE"
    },
    {
      "videoName": "יום הולדת 27",
      "videoSubTitle": "",
      "videoDesc": "כולם מרימים לחיים לכבוד אחד הגברים הצעירים שחוגג יום הולדת. מדברים על הגיל שלו.",
      "menAndWomen": "הנשים יושבות בראש השולחן והגברים מסביב.",
      "childrenAndParents": "אין יחסים ברורים",
      "year": 2015,
      "lang": "hebrew",
      "relation": 3,
      "": "",
      "foodAndDrink": "mizrahi-2, ashkenazi-20, alcohol7",
      "event": "bday",
      "subjects": "memory-0",
      "emotions": "happy-13",
      "objects": "chairs-24, tools-33, art-31",
      "videoFileName": "27 יום הולדת",
      "isAutoPlay": "TRUE",
      "videoInformation": "desc-אין, views-25, profile-רני גולדמן, subscribers-24",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב בבית משפחת נעים",
      "videoSubTitle": 11.1992,
      "videoDesc": "הנשים מסביב לשולחן עם הילדים. מדברות עם הילדים על האוכל. אז מצטרף גם הגבר לשולחן.",
      "menAndWomen": "אחד הגברים מצלם והשני יושב בראש השולחן. הנשים יושבות עם הילדים.",
      "childrenAndParents": "הנשים יושבות ליד הילדים שלהן ודואגות לאוכל שלהם.",
      "year": 1992,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-7",
      "event": "friday",
      "subjects": "food-1, politiks-32",
      "emotions": "laugh-28, anger-36",
      "objects": "tools-19",
      "videoFileName": "ארוחת ערב בבית משפחת נעים 111992",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-60, profile-Pierre Benisti, subscribers-1",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב שבת אצל רותי וגדעון",
      "videoSubTitle": "9/11/2007",
      "videoDesc": "כולם אוכלים מוציא של קידוש, אחד הגברים הצעירים מנשק את האחר והוא לא נענה לו וננזף על ידי אמו.",
      "menAndWomen": "יש רוב גברי. הגברים הצעירים עמדו בעוד האישה המבוגרת ישבה.",
      "childrenAndParents": "האם נוזפת באחד הילדים וגם נעזרת בו.",
      "year": 2007,
      "lang": "hebrew",
      "relation": 3,
      "": "",
      "foodAndDrink": "mizrahi-17",
      "event": "friday",
      "subjects": "memory-10",
      "emotions": "laugh-12, happy-5",
      "objects": "tools-27",
      "videoFileName": "ארוחת ערב שבת אצל רותי וגדעון 9112007",
      "isAutoPlay": "",
      "videoInformation": "desc-ארז ואני אצל ההורים בערב שישי, views-273, profile-tamilov, subscribers-12",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב",
      "videoSubTitle": "",
      "videoDesc": "הילדים יושבים עם אבא שלהם לאכול ארוחת ערב. האמא מצלמת. יש ויכוחים בין הילדים.",
      "menAndWomen": "הגבר בשולחן עם הילדים, עוזר להם. האישה מצלמת.",
      "childrenAndParents": "האבא מסביר לילד הגדול שלו כל מיני דברים, ומנסה להרגיע את הילד הקטן.",
      "year": 2012,
      "lang": "hebrew, english",
      "relation": 3,
      "": "",
      "foodAndDrink": "bread-8, ashkenazi-6",
      "event": "other",
      "subjects": "food-10, politiks-29",
      "emotions": "happy-2, laugh-52, anger-18",
      "objects": "tools-0",
      "videoFileName": "ארוחת ערב",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-181, profile-Itamar Simhon, subscribers-1",
      "isCrop": ""
    },
    {
      "videoName": "מימונה אצל שמעון אברג'ל",
      "videoSubTitle": "",
      "videoDesc": "אחד הגברים רוקד לצלילי מוזיקה של להקה חיה ומצטרפים אליו נוספים. רוב האנשים יושבים מסביב.",
      "menAndWomen": "הגברים במרכז העניינים, הנשים יושבות בצד או נמצאות במטבח.",
      "childrenAndParents": "אין",
      "year": 2011,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "",
      "event": "holiday",
      "subjects": "",
      "emotions": "happy-0",
      "objects": "light-6, communication-11, art-3",
      "videoFileName": "מימונה אצל שמעון אברגל",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-324, profile-ישראל הכריש (ישראל הכריש), subscribers-571",
      "isCrop": ""
    },
    {
      "videoName": "בת מצווה מיכל קרת",
      "videoSubTitle": "",
      "videoDesc": "דני",
      "menAndWomen": "מתבקש מהגברים להרים את הנערה על הכיסא. הנשים מצטרפות.",
      "childrenAndParents": "ההורים של הנערה סביבה, מחבקים אותה ושמים לה זר.",
      "year": 2011,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "dessert-0",
      "event": "bday",
      "subjects": "memory-0",
      "emotions": "happy-2, laugh-52",
      "objects": "communication-23",
      "videoFileName": "בת מצווה מיכל קרת",
      "isAutoPlay": "",
      "videoInformation": "desc-על האש אצל גיל, views-106, profile-Gerry abramovich, subscribers-0",
      "isCrop": ""
    },
    {
      "videoName": "mizrahi-26, alcohol-54",
      "videoSubTitle": "",
      "videoDesc": "הילד על רגליה של אחת הנשים, שרים איתו ומתנהלת שיחה במקביל.",
      "menAndWomen": "הנשים שרות עם הילד בזמן שהגברים משוחחים על נושא אחר.",
      "childrenAndParents": "הילד יושב על אישה שאינה אמא שלו, אמא שלו מתחילה לשיר איתו.",
      "year": 2011,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-26, alcohol-2",
      "event": "friday",
      "subjects": "memory-0",
      "emotions": "happy-8, laugh-39",
      "objects": "",
      "videoFileName": "ארוחת שבת אצל דורון וניצי",
      "isAutoPlay": "",
      "videoInformation": "desc-זיוי מצייר עם דודה אורית, views-53, profile-Barak Fridman, subscribers-18",
      "isCrop": ""
    },
    {
      "videoName": "מיגל איתי ותמר בחלק אומנותי",
      "videoSubTitle": "לאחר ארוחת חג 24.4.2011",
      "videoDesc": "האבא עושה לשאר המשפחה הופעה עם שני הילדים שלו והם כולם שרים ביחד שיר בספרדית.",
      "menAndWomen": "הגבר שר ורוקד עם הילדים, האישה צופה מה\"קהל",
      "childrenAndParents": "האבא והילדים נראים מאוד קרובים.",
      "year": 2011,
      "lang": "hebrew, espanol",
      "relation": 2,
      "": "",
      "foodAndDrink": "",
      "event": "holiday",
      "subjects": "memory-0",
      "emotions": "happy-10, laugh-43, embarrassment-27",
      "objects": "art-4, communication-8",
      "videoFileName": "מיגל איתי ותמר בחלק אומנותי לאחר ארוחת חג 24.4.2011",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-42, profile-Uri Katz, subscribers-22",
      "isCrop": ""
    },
    {
      "videoName": "אל האש אצל קטי",
      "videoSubTitle": "",
      "videoDesc": "הגברים מדברים ביניהם ועם הילד במרפסת תוך כדי ההתעסקות עם המנגל. הם צוחקים איתו/עליו. בפנים רואים את האישה מסדרת את שולחן האוכל ולידה ילד נוסף.",
      "menAndWomen": "הגברים בחוץ מטפלים בבשר ובמנגל, האישה בפנים מסדרת את השולחן ושאר האוכל.",
      "childrenAndParents": "כל ילד עם הורה אחר. האב מתבדח עם הילד שאיתו.",
      "year": 2017,
      "lang": "hebrew, ruski",
      "relation": 3,
      "": "",
      "foodAndDrink": "mizrahi- 10",
      "event": "holiday",
      "subjects": "food-5",
      "emotions": "laugh-11",
      "objects": "chairs-31, art-33",
      "videoFileName": "אל האש אצל קטי",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-22, profile-Michael Mazyar, subscribers-10",
      "isCrop": ""
    },
    {
      "videoName": "אלי מזור אצל נועם רוית",
      "videoSubTitle": "פסח 2019",
      "videoDesc": "אחד הגברים מפייט חלק מההגדה. בינתיים הילדה דורשת תשומת לב ורוצה לאכול פיצה. נראה כי הגבר שמפייט לא מרוצה מנוכחות המצלמה ברגע שמבחין בה.",
      "menAndWomen": "כולם מצטרפים לפיוטי הגבר בשלב מסוים.",
      "childrenAndParents": "רוב הילדים יושבים בחלק נפרד בשולחן מההורים שלהם. הילדה הקטנה רוצה לאכול ואמה עוזרת לה.",
      "year": 2019,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "alcohol-23",
      "event": "holiday",
      "subjects": "text-0, politiks-16",
      "emotions": "calm-64, anger-68",
      "objects": "tools-26, art-3",
      "videoFileName": "אלי מזור פסח 2019 אצל נועם _ רוית",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-12, profile-אלי מזור, subscribers-27",
      "isCrop": ""
    },
    {
      "videoName": "חגיגות יום העצמאות אצל יעקב",
      "videoSubTitle": "עושים על האש(1)",
      "videoDesc": "כולם יושבים מסביב לשולחן ומנהלים שיחות בקבוצות קטנות.",
      "menAndWomen": "יושבים מעורב",
      "childrenAndParents": "אין",
      "year": 2017,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-4",
      "event": "bbq",
      "subjects": "memory-0",
      "emotions": "embarrassment-23",
      "objects": "",
      "videoFileName": "חגיגות יום העצמאות אצל יעקב עושים על האש(1)",
      "isAutoPlay": "",
      "videoInformation": "desc-ארב מהנה אם משפחה בערב יום העצמאות\n, views-52, profile-יעקב צרפתי, subscribers-19",
      "isCrop": "FALSE"
    },
    {
      "videoName": "אצל רותי וג'ק",
      "videoSubTitle": "24.8.2002",
      "videoDesc": "המבוגרים יושבים בסלון בנחת, שאר האנשים מפוזרים בחלל, כל אחד עסוק בעניניו. לאחת הנשים הצעירות יש יום הולדת וחוגגים לה ללא נוכחות כל האנשים.",
      "menAndWomen": "המארחות עסוקות בסדר וארגון, הגברים יושבים בסלון.",
      "childrenAndParents": "אמה של התינוקת יושבת לצידה, אביה (הצלם) נותן לתינוקת יחס ומקפיד לצלם אותה.",
      "year": 2002,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "dessert-0",
      "event": "bday",
      "subjects": "memory-42",
      "emotions": "happy-28, calm-25",
      "objects": "tools-4, communication-10",
      "videoFileName": "אצל רותי וג'ק 24.8.2002",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-3, profile-Lior Mashaal, subscribers-77",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת החג אצל חנהלה",
      "videoSubTitle": "",
      "videoDesc": "האנשים יושבים סביב לשולחן, מדברים על המצלמה ומתעסקים בצילום, בהרגלי האכילה של הצלם ובמנה הבאה.",
      "menAndWomen": "המארחת ובתה הן אלו שדואגות להגשת האוכל, הגברים יושבים לשולחן.",
      "childrenAndParents": "הבת של המארחת עוזרת לה במטבח.",
      "year": 2011,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-3",
      "event": "holiday",
      "subjects": "food-34, photography-7",
      "emotions": "laugh-35",
      "objects": "chairs-87, tools-20, art-1",
      "videoFileName": "ארוחת החג אצל חנהלה",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-57, profile-merkelchaim, subscribers-1",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב שישי אצל ברכה ושמואל",
      "videoSubTitle": "14.3.14",
      "videoDesc": "הצלם מספר על האירוע, הנשים מדברות על המפה. האישה המבוגרת מתעסקת באוכל. מבקשים מהצלם להפסיק לצלם",
      "menAndWomen": "האישה המבוגרת מתעסקת באוכל, השאר יושבים לשולחן.",
      "childrenAndParents": "הילדים חסרי סבלנות ויושבים ליד ההורים שעוזרים להם.",
      "year": 2014,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "alcohol-10, bread-48, ashkenazi-42",
      "event": "friday",
      "subjects": "food-54, photography-85, politiks-67",
      "emotions": "happy-26, laugh-78, anger-88",
      "objects": "chairs-13, tools-1",
      "videoFileName": "ארוחת ערב שישי אצל ברכה ושמואל 14.3.14",
      "isAutoPlay": "",
      "videoInformation": "desc-ארוחת ערב עם משפחת לוקץ' !, views-178, profile-אריה בן-אברהם, subscribers-58",
      "isCrop": ""
    },
    {
      "videoName": "ליל סדר פרסי",
      "videoSubTitle": "מנהג הבצלים",
      "videoDesc": "כולם יושבים מסביב לשולחן ולוקחים בצל ירוק. הגברים מורידים חולצה ומתחילים להצליף אחד בשני עם הבצל כמנהג המסורת.",
      "menAndWomen": "הנשים בניגוד לגברים לא לוקחות חלק במנהג.",
      "childrenAndParents": "הבנים והאבות מצליפים אחד בשני בבצל.",
      "year": 2009,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-83, ashkenazi-49",
      "event": "holiday",
      "subjects": "text-196, photography-87",
      "emotions": "happy-0, laugh-12",
      "objects": "light-17, art-3",
      "videoFileName": "ליל סדר פרסי  מנהג הבצלים",
      "isAutoPlay": "",
      "videoInformation": "desc-דיינו בליל הסדר במשפחה פרסית\nתחילת השיר \"דיינו \", views-46,736, profile-avi81183, subscribers-15",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת שישי אצל סבתא שולה",
      "videoSubTitle": "",
      "videoDesc": "הסרטון מיועד למישהו שלא נמצא באירוע, ורוב האנשים מדברים למצלמה. האחרים בשיחה נפרדת.",
      "menAndWomen": "האמא עם הילד שלה ולא והאבא הוא הצלם. כולם יושבים במעורב ומנהלים שיחות מגוונות.",
      "childrenAndParents": "הילד הקטן עם אמו על המיטה.",
      "year": 2010,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-136, ashkenazi-143",
      "event": "friiday",
      "subjects": "memory-66, photography-10",
      "emotions": "laugh-13",
      "objects": "light-55, tools-141, art-48",
      "videoFileName": "ארוחת שישי אצל סבתא שולה",
      "isAutoPlay": "",
      "videoInformation": "desc-ארוחה, views-124, profile-donna8879, subscribers-3",
      "isCrop": ""
    },
    {
      "videoName": "יום עצמאות אצל משפחת וייס & פלישר",
      "videoSubTitle": "בירושלים 2013",
      "videoDesc": "הצלמת מצלמת את המנגל ושואלת שאלות את הגבר שמתעסק איתו.",
      "menAndWomen": "גבר מתפעל את המנגל.",
      "childrenAndParents": "הילדה של הצלמת מבקשת ממנה לשבת, נשמע כדי שלא יהיה לה קשה לעמוד.",
      "year": 2013,
      "lang": "hebrew",
      "relation": 3,
      "": "",
      "foodAndDrink": "mizrahi-0",
      "event": "bbq",
      "subjects": "food-42",
      "emotions": "laugh-33",
      "objects": "",
      "videoFileName": "יום עצמאות בירושלים  2013 אצל משפחת וייס & פלישר",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-22, profile-Rachel Suranyi, subscribers-3.23K",
      "isCrop": ""
    },
    {
      "videoName": "פסח על האש",
      "videoSubTitle": 2013,
      "videoDesc": "המבוגרים מדברים עם ועל הילד. הילד וסבתו צוחקים על סרטון.",
      "menAndWomen": "כולם שותפים שווים לישיבה.",
      "childrenAndParents": "הילד עם ההורים שלו אבל גם מטייל בין כל המבוגרים האחרים.",
      "year": 2013,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "",
      "event": "holiday",
      "subjects": "politiks-2",
      "emotions": "laugh-5",
      "objects": "tools-1",
      "videoFileName": "פסח על האש 2013",
      "isAutoPlay": "",
      "videoInformation": "desc-על האש אצל מלכה באלפי מנשה, views-50, profile-ששון אלמוזלינו, subscribers-3",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת שישי עם משפ' חסון",
      "videoSubTitle": "אצל סבתא נדיה (2003)",
      "videoDesc": "שני הגברים עומדים בזמן שאחד מהם עושה את הקידוש והמוציא, כל שאר בני המשפחה יושבים לשולחן ומדברים. ברקע יש טלוויזיה פועלת.",
      "menAndWomen": "הגברים עושים את הקידוש ויושבים בראש השולחן. הנשים יושבות מסביב.",
      "childrenAndParents": "האמא צוחקת עם ילדיה.",
      "year": 2003,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-28, bread-56",
      "event": "friday",
      "subjects": "food-39, text-0",
      "emotions": "happy-15",
      "objects": "light-3",
      "videoFileName": "ארוחת שישי עם משפ' חסון אצל סבתא נדיה (2003)",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-24, profile-shay bc, subscribers-120",
      "isCrop": ""
    },
    {
      "videoName": "אצל משפחת רוזן",
      "videoSubTitle": "ארוחת ערב שישי שהכינה אילת קופר",
      "videoDesc": "מדברים על האוכל והכנתו סביב השולחן, הגברים המבוגרים מפרגנים בצורה מגוכחת וצוחקים על השיח שהתפתח.",
      "menAndWomen": "הנשים מדברות על אופן הבישול של אחת המנות, הגברים מגכחים על כך מהצד.",
      "childrenAndParents": "הילדים בוגרים, אין יחס ברור בין ההורים לילדיהם.",
      "year": 2012,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-35, ashkenazi-32, alcohol-27",
      "event": "friday",
      "subjects": "food-1, photography-15",
      "emotions": "happy-64, laugh-51",
      "objects": "tools-38, art-43",
      "videoFileName": "אצל משפחת רוזן, ארוחת ערב שישי שהכינה אילת קופר  9.2012 אילנה",
      "isAutoPlay": "TRUE",
      "videoInformation": "desc-אין, views-122, profile-avi rosen, subscribers-1.15K",
      "isCrop": ""
    },
    {
      "videoName": "עצמאות 2015",
      "videoSubTitle": "הגשם הרס את החגיגות על האש אבל אנחנו נשארנו עד הסוף",
      "videoDesc": "מישהו נתפס מוציא לכלוך מהשן במצלמה. הצלם עובר בין הסובבים ומנסה להרקיד אותם לצלילי המוזיקה ברקע.",
      "menAndWomen": "רוב הגברים יושבים, רוב הנשים סביב האוכל.",
      "childrenAndParents": "רוב הילדים מרוכזים בפינה אחת עם אחת האמהות.",
      "year": 2015,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "alcohol-8, ashkenazi-5",
      "event": "bbq",
      "subjects": "memory-0, politiks-14",
      "emotions": "laugh-7, embarrassment-3",
      "objects": "chairs-44, tools-1",
      "videoFileName": "עצמאות 2015 הגשם הרס את החגיגות על האש אבל אנחנו נשארנו עד הסוף",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-108, profile-‫שרון מלכה יוטיובר sharon malka (‪sharon malka‬‏), subscribers-12.3K",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת חג ראש השנה",
      "videoSubTitle": "",
      "videoDesc": "הגבר מברך לכבוד השנה החדשה. אישה אחת מביטה בו והשניה מצלמת. לאחר מכן הם מתיישבים לאכול.",
      "menAndWomen": "הגבר מברך, הנשים מביטות בו.",
      "childrenAndParents": "אין",
      "year": 2017,
      "lang": "hebrew",
      "relation": 3,
      "": "",
      "foodAndDrink": "mizrahi-19, ashkenazi-21, alcohol-18",
      "event": "holiday",
      "subjects": "memory-0",
      "emotions": "calm-4",
      "objects": "chairs-10, tools-16",
      "videoFileName": "ארוחת חג ראש השנה",
      "isAutoPlay": "",
      "videoInformation": "desc-פיקשוש, views-127, profile-אליעזר מלכה, subscribers-1",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת יום ההולדת לעדי",
      "videoSubTitle": "ספטמבר 2011",
      "videoDesc": "אחד הגברים מתחיל בקידוש והאישה עוצרת אותו ומספרת על האוכל. כולם מדברים למצלמה ומתארים למישהי שלא נוכחת את האוכל והמתכון של העוף.",
      "menAndWomen": "הגברים יושבים בצד אחד של השולחן והנשים בצד השני.",
      "childrenAndParents": "אין",
      "year": 2011,
      "lang": "hebrew",
      "relation": 3,
      "": "",
      "foodAndDrink": "mizrahi-8, ashkenazi-2",
      "event": "bday",
      "subjects": "text-0, food-6",
      "emotions": "happy-10",
      "objects": "chairs-28, tools-23",
      "videoFileName": "ארוחת יום ההולדת לעדי ספטמבר 2011",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-33, profile-Dani Harel, subscribers-0",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב טיפוסית",
      "videoSubTitle": "",
      "videoDesc": "ילדים ליד שולחן האוכל עם אבא שלהם שמצלם. הוא מבקש מהם להגיד \"בתיאבון\" למצלמה ומצלם את האוכל על השולחן וההכנות.",
      "menAndWomen": "אין",
      "childrenAndParents": "האב אומר לילדים מה לעשות והם עושים.",
      "year": 2014,
      "lang": "hebrew",
      "relation": 3,
      "": "",
      "foodAndDrink": "ashkenazi-17",
      "event": "other",
      "subjects": "food-3",
      "emotions": "calm-1, embarrassment-7",
      "objects": "tools-14",
      "videoFileName": "ארוחת ערב טיפוסית",
      "isAutoPlay": "TRUE",
      "videoInformation": "desc-וברכת ערב טוב לצופים, views-318, profile-Elya Eshel, subscribers-29",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת שישי אצל גוזי",
      "videoSubTitle": "",
      "videoDesc": "אחד הגברים עושה קידוש וכולם עומדים ואומרים בסוף אמן.",
      "menAndWomen": "גבר עושה את הקידוש, אישה יושבת בראש השולחן.",
      "childrenAndParents": "אין",
      "year": 2016,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-3",
      "event": "friday",
      "subjects": "text-0",
      "emotions": "",
      "objects": "tools-11",
      "videoFileName": "ארוחת שישי אצל גוזי",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-20, profile-David Mesika, subscribers-48",
      "isCrop": "FALSE"
    },
    {
      "videoName": "ארוחת שישי אצל אבלין פדידה",
      "videoSubTitle": "",
      "videoDesc": "כולם לבקשת הצלם מדברים למצלמה לאמא שלו שלכבודה הסרטון.",
      "menAndWomen": "אחד הגברים צוחק ש\"אישה טובה היתה דואגת למלח",
      "childrenAndParents": "הילדים יושבים בנפרד מההורים שלהם.",
      "year": 2016,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-5, ashkenazi-2",
      "event": "friday",
      "subjects": "memory-30, photography-10",
      "emotions": "laugh-40",
      "objects": "chairs-0, tools-2",
      "videoFileName": "ארוחת שישי אצל אבלין פדידה",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-13, profile-Omri Levy, subscribers-52",
      "isCrop": ""
    },
    {
      "videoName": "יום של כיף",
      "videoSubTitle": "עושים על האש3",
      "videoDesc": "כולם יושבים מסביב לשולחן, חלק שרים ביחד עם המוזיקה ומוחאים כפיים בסוף השיר.",
      "menAndWomen": "משתתפים באופן שווה בחגיגה",
      "childrenAndParents": "אין",
      "year": 2018,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "",
      "event": "bbq",
      "subjects": "memory-0",
      "emotions": "happy-15",
      "objects": "chairs-12, tools-7",
      "videoFileName": "יום של כיף עושים על האש3",
      "isAutoPlay": "",
      "videoInformation": "desc-נהנים בחיק המשפחה\n, views-13, profile-יעקב צרפתי, subscribers-19",
      "isCrop": ""
    },
    {
      "videoName": "אריה וטלי טייב פסח אצל סבתא יהודית מזרחי",
      "videoSubTitle": "2017 במודיעין",
      "videoDesc": "כולם סביב השולחן עושים חלק מהסדר.",
      "menAndWomen": "גבר יושב בראש השולחן. אישה מביאה דברים מהמטבח בזמן הברכות. מסביב יושבים מעורב.",
      "childrenAndParents": "הילדים יושבים לים ההורים. אחת הילדה הקטנה יושבת בין ההורים שלה ואבא שלה מדבר איתה ומצלם.",
      "year": 2017,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-21",
      "event": "holiday",
      "subjects": "text-0, politiks-47",
      "emotions": "",
      "objects": "light-18, tools-38, communication-33, art-14",
      "videoFileName": "אריה וטלי טייב פסח 2017 במודיעין אצל סבתא יהודית מזרחי והילדים אהוד ושירה  טייב",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-36, profile-אריה.פוליש קריסטל.ניקוי ספות. ציפוי אמבטיה. טייב, subscribers-2.85K",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת שישי למשפחת מוסן",
      "videoSubTitle": "אצל רונית",
      "videoDesc": "כולם עומדים מסביב לשולחן ושרים \"שלום עליכם",
      "menAndWomen": "גברים יושבים בראש השולחן. בשאר השולחן הישיבה מעורבת.",
      "childrenAndParents": "אין",
      "year": 2016,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "mizrahi-2, ashkenazi-4",
      "event": "friday",
      "subjects": "text-0",
      "emotions": "",
      "objects": "light-9, tools-4, art-12",
      "videoFileName": "ארוחת שישי למשפחת מוסן אצל רונית",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-29, profile-David Mesika, subscribers-48",
      "isCrop": ""
    },
    {
      "videoName": "על האש אצל לבנה ומאיר",
      "videoSubTitle": 1988,
      "videoDesc": "הילדים אוכלים בשולחן הילדים ושמים לב למצלמה. המצלמה עוברת בין כל האנשים ומצלמת את ההתרחשות מהצד.",
      "menAndWomen": "הגברים מתפעלים את המנגל, הנשים יושבות לשולחן או מתעסקות עם הסירים.",
      "childrenAndParents": "רוב הילדים עצמאיים ולא נמצאים ליד ההורים. ילדה אחת על הידיים של אמא שלה.",
      "year": 1988,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-24, bread-17",
      "event": "bbq",
      "subjects": "photography-4",
      "emotions": "happy-17, laugh-39",
      "objects": "",
      "videoFileName": "על האש אצל לבנה ומאיר 1988",
      "isAutoPlay": "",
      "videoInformation": "desc-קרית אתא  21.4.1988, views-27, profile-צבי דר, subscribers-9",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת שישייום הולדת אהרון",
      "videoSubTitle": "",
      "videoDesc": "מעבירים מאחד לאחד את כוס הקידוש. האמא שמה לכל אחד בצלחת את מה שהוא רוצה.",
      "menAndWomen": "הגבר עשה את הקידוש והאישה (אמא שלו) היא שמביאה את האוכל מהמטבח.",
      "childrenAndParents": "הילדים יושבים לשולחן בזמן שאמא שלהם מביאה להם את האוכל. היא מתבאסת כשאחד הילדים מתפעל בסלטים שהכין ולא מפרגן לה על הבישולים.",
      "year": 2014,
      "lang": "hebrew",
      "relation": 3,
      "": "",
      "foodAndDrink": "alcohol-0",
      "event": "friday",
      "subjects": "food-6",
      "emotions": "happy-30, anger-34",
      "objects": "communication-2",
      "videoFileName": "ארוחת שישייום הולדת אהרון",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-88, profile-Zahava Shmuel, subscribers-0",
      "isCrop": ""
    },
    {
      "videoName": "פסח אצל ערן ואורנית",
      "videoSubTitle": "18.4.11",
      "videoDesc": "הצלם מצלם את השולחן והאנשים ורודה בסובבים שמהשאירו תיקים בחוץ. יש כל מיני שיחות סביב ועם הילדים.",
      "menAndWomen": "אין",
      "childrenAndParents": "האמהות סביב הילדות שלהן.",
      "year": 2011,
      "lang": "hebrew, english",
      "relation": 1,
      "": "",
      "foodAndDrink": "alcohol-6, ashkenazi-8",
      "event": "holiday",
      "subjects": "politiks-10, photography-38",
      "emotions": "happy-24",
      "objects": "chairs-82, tools-2",
      "videoFileName": "פסח אצל ערן ואורנית   18.4.11",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-88, profile-אריה בן-אברהם, subscribers-58",
      "isCrop": ""
    },
    {
      "videoName": "ליל סדר אצל משפחת חקלאי",
      "videoSubTitle": "",
      "videoDesc": "כולם יושבים מסביב לשולחן ושרים את הברכה. אחד הגברים מקיים את הברכה מעל הראש של כל אחד עד שהצלמת ממשיכה אותו.",
      "menAndWomen": "גם גבר וגם אישה קיימו את הברכה. ישיבה מעורבת.",
      "childrenAndParents": "אין",
      "year": 2012,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "",
      "event": "holiday",
      "subjects": "text-8, photography-38",
      "emotions": "embarrassment-0",
      "objects": "art-18, communication-3",
      "videoFileName": "ליל סדר אצל משפחת חקלאי",
      "isAutoPlay": "",
      "videoInformation": "desc-ליל סדר עם המשפחות לשושלת ביטון, views-194, profile-meir maman, subscribers-15",
      "isCrop": "FALSE"
    },
    {
      "videoName": "אצל מיכל וקובי",
      "videoSubTitle": "אפריל 2011",
      "videoDesc": "הילדה שרה והמבוגרים מרוצים ומריעים לה. הסבתא ברקע שואלת על היחס של הגננות לילדה. נוצר שיח סביב הסיפור של משה בתיבה.",
      "menAndWomen": "ישנו שיתוף פעולה מלא בין הגברים לנשים בשיח.",
      "childrenAndParents": "אמה של הילדה לצידה, גאה בה, מנחה אותה ומשוחחת איתה בסבלנות. ניתן להניח שהאב הוא הצלם.",
      "year": 2011,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "dessert-14",
      "event": "other",
      "subjects": "text-0, politiks-42",
      "emotions": "happy-16, calm-11",
      "objects": "chairs-10, tools-21",
      "videoFileName": "אפריל 2011 אצל מיכל וקובי",
      "isAutoPlay": "",
      "videoInformation": "desc-על האש, פסח 2011\n, views-53, profile-Behar's Family, subscribers-152",
      "isCrop": ""
    },
    {
      "videoName": "על האש",
      "videoSubTitle": "",
      "videoDesc": "מוזיקה ברקע. הגבר שעל המנגל רוקד עד שמבין שהוא מצולם ואז מאחל איחולים למצלמה. אישה נוספת מצטרפת לריקודים.",
      "menAndWomen": "גבר מתפעל את המנגל, הנשים מסתובבות בחלל.",
      "childrenAndParents": "הילדה עצובה כשאמא שלה הולכת ממנה. הצלמת רוצה לשלוח לאמא שלה את הסרטון.",
      "year": 2008,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "",
      "event": "bbq",
      "subjects": "photography-5",
      "emotions": "happy-7, laugh-12, anger-33",
      "objects": "chairs-1",
      "videoFileName": "על האש",
      "isAutoPlay": "",
      "videoInformation": "desc-אצל דליה, views21-, profile-hilaelbaz2, subscribers-0",
      "isCrop": ""
    },
    {
      "videoName": "על האש אצל אורית",
      "videoSubTitle": "",
      "videoDesc": "האנשים מפוזרים בחלקים שונים בשיחות שונות ברחבי הבית. חלק מגיבים למצלמה. הילד תופס את תשומת ליבה של הצלמת.",
      "menAndWomen": "חלק מהגברים בחוץ מתפעלים את המנגל, חלק מהנשים במטבח. אמא אחת נמצאת עם הילדים שלה.",
      "childrenAndParents": "האמא הצעירה עם הילדים הקטנים שלה, מאכילה את האחד ושומרת על השני.",
      "year": 2014,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "mizrahi-3, ashkenazi-64",
      "event": "bbq",
      "subjects": "pilitiks-39, photography-13",
      "emotions": "happy-26",
      "objects": "tools-0, communication-41",
      "videoFileName": "על  האש אצל אורית",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-18, profile-Amira Meirfeld, subscribers-15",
      "isCrop": ""
    },
    {
      "videoName": "עומר יום הולדת 13",
      "videoSubTitle": "",
      "videoDesc": "ילד היום הולדת מתבקש לבקש משאלה ולא מצליח לכבות את הנרות. לבסוף כשמצליח שרים לו שירי יום הולדת בעברית ואנגלית.",
      "menAndWomen": "אין",
      "childrenAndParents": "אמא של ילד היום הולדת מצלמת ואביו דואג לעוגה. אבא שלו טופח על ראשו בחיבה.",
      "year": 2013,
      "lang": "hebrew, english",
      "relation": 2,
      "": "",
      "foodAndDrink": "dessert-17",
      "event": "bday",
      "subjects": "memory-34",
      "emotions": "happy-31, laugh-23, embarrassment-3",
      "objects": "tools-75",
      "videoFileName": "עומר יום הולדת 13",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-59, profile-Dafna Pinto, subscribers-0",
      "isCrop": ""
    },
    {
      "videoName": "זיו ונעמה אוכלים ארוחת ערב",
      "videoSubTitle": "",
      "videoDesc": "הצלם מבקש מהילד שיגיד דברים לסבתא שלו שלכבודה מצולם הסרטון בזמן ארוחת הערב. הילד לא כל כך מתלהב והילדה משתתפת.",
      "menAndWomen": "אין",
      "childrenAndParents": "האבא יושב בין שני הילדים ומנסה לדובב אותם לסרטון בזמן.",
      "year": 2014,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "",
      "event": "other",
      "subjects": "memory-20, photography-0",
      "emotions": "embarrassment-7",
      "objects": "tools-3",
      "videoFileName": "זיו ונעמה אוכלים ארוחת ערב",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-64, profile-Barak Fridman, subscribers-18",
      "isCrop": "FALSE"
    },
    {
      "videoName": "ארוחת ערב ראש השנה",
      "videoSubTitle": "תשס\"ט",
      "videoDesc": "אחת הנשים מצולמת מדברת בטלפון עם האישה שלכבודה מצולם הסרטון. בסלון נפתחות מתנות ומדברים עליהן.",
      "menAndWomen": "מבלים ביחד",
      "childrenAndParents": "הילדים מביאים מתנות לאמא שלהם. האב מצלם את הבת שלו.",
      "year": 2008,
      "lang": "hebrew, espanol",
      "relation": 3,
      "": "",
      "foodAndDrink": "",
      "event": "holiday",
      "subjects": "memory-19, photography-30",
      "emotions": "happy-34",
      "objects": "chairs-29, communication-0",
      "videoFileName": "ארוחת ערב ראש השנה תשסט",
      "isAutoPlay": "",
      "videoInformation": "desc-אצל סבא וסבתא, views-144, profile-Yosi Ben Ruby, subscribers-15",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת יום שישי אצל סבתא",
      "videoSubTitle": "המשך",
      "videoDesc": "הסרטון נפתח בצילום של בלון הליום ללא הליום מאירוע חתונה. הצלם חיצוני לסיטואציה ומצלם את כולם סביב שולחן האוכל שותים שתיה חמה ומדברים.",
      "menAndWomen": "רוב נשי. הגבר יושב באחד מראשי השולחן.",
      "childrenAndParents": "אין",
      "year": 2014,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "",
      "event": "other",
      "subjects": "",
      "emotions": "calm-5",
      "objects": "chairs-16, communication-20",
      "videoFileName": "ארוחת יום שישי אצל סבתא המשך 11.2014",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-38, profile-שבט חמציק ורבקה, subscribers-2",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת חג הפסח",
      "videoSubTitle": "",
      "videoDesc": "כולם אוכלים, מדברים על האוכל וברקע הילדים רואים טלוויזיה בעגלות.",
      "menAndWomen": "הנשים מנהלות את הארוחה ומציעות אוכל, הגברים יושבים לשולחן.",
      "childrenAndParents": "ההורים יושבים לשולחן והילדים מהופנטים לטלוויזיה. אחת האמהות מאכילה את התינוק שלה.",
      "year": 2010,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-7, ashkenazi-4",
      "event": "holiday",
      "subjects": "food-10",
      "emotions": "calm-2",
      "objects": "chairs-21, tools-0",
      "videoFileName": "ארוחת חג הפסח.MP4",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-194, profile-alonchen1, subscribers-23",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת חג ערהש",
      "videoSubTitle": "הקופרים והרוזנים אילנה רוזן",
      "videoDesc": "לא כולם התיישבו לשולחן, מדברים על האוכל ובינתיים הנשים מביאות עוד דברים לשולחן. הגברים מפארים את האוכל.",
      "menAndWomen": "הנשים מתעסקות עם הגשת האוכל לשולחן, הגברים יושבים לשולחן ומדברים על האוכל.",
      "childrenAndParents": "הילד הצעיר יושב לשולחן ומרוכז בטלפון שלו, לא מתקשר עם ההורים.",
      "year": 2012,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "mizrahi-11, ashkenazi-16, alcohol-22",
      "event": "holiday",
      "subjects": "food-0",
      "emotions": "happy-37",
      "objects": "art-33",
      "videoFileName": "ארוחת חג ערהש הקופרים והרוזנים אילנה רוזן",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-35, profile-avi rosen, subscribers-1.15K",
      "isCrop": ""
    },
    {
      "videoName": "ביום העצמאות על האש",
      "videoSubTitle": "חלק ב' 16.4.13",
      "videoDesc": "כולם יושבים לשולחן שמורכב משני שולחנות. מדברים על השוני בארוחות בין הצדדים במשפחה.",
      "menAndWomen": "ישיבה מעורבת",
      "childrenAndParents": "הילד הקטן בראש השולחן ליד אביא שלו שמאכיל אותו. הילד הגדול יושב עם הגדולים ללא קשר עם ההורים שלו.",
      "year": 2013,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "ashkenazi-9, mizrahi-3",
      "event": "bbq",
      "subjects": "food-22, memory-24",
      "emotions": "anger-10",
      "objects": "light-20, tools-0, art-73",
      "videoFileName": "ביום העצמאות על האש חלק ב'  16.4.13",
      "isAutoPlay": "",
      "videoInformation": "desc-עם הפלורנטינים על האש בחג העצמאות אצל סבתא מזל, views-79, profile-אריה בן-אברהם, subscribers-58",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת בוקר אצל סבא הלל",
      "videoSubTitle": "",
      "videoDesc": "תינוקת בכיסא תינוק אוכלת ארוחת בוקר עם סבא שלה, אביה מצצלם אותם ואת בת זוגתו שבמטבח והיא מתעצבנת.",
      "menAndWomen": "האישה שוטפת כלים, בזמן שהגברים עסוקים בהאכלת הילדה.",
      "childrenAndParents": "הסבא מאכיל את הילדה ולא הוריה.",
      "year": 2009,
      "lang": "hebrew, english",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-65",
      "event": "other",
      "subjects": "food-14, photography-41",
      "emotions": "laugh-37, anger-44",
      "objects": "",
      "videoFileName": "ארוחת בוקר אצל סבא הלל",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-72, profile-Boaz Hachlili, subscribers-14",
      "isCrop": ""
    },
    {
      "videoName": "קזן 38",
      "videoSubTitle": "13 12 2012 אחרי הארוחה",
      "videoDesc": "הילדים הגדולים מחשקים בחדר נפרד ללא ההורים והילדים הקטנים נמצאים עם ההורים בחלל המרכזי.",
      "menAndWomen": "אלבומי תמונות מפוזרים אצל המבוגרים והילדים מצטרפים. המבוגרים מעלים זכורונות. הצלפ עובר לצלם את הילדים בחללים האחרים.",
      "childrenAndParents": "אישה עם תינוקת, אין כמעט גברים בחלל.",
      "year": 2012,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "",
      "event": "friday",
      "subjects": "memory-11",
      "emotions": "happy-9, laugh-48",
      "objects": "art-41, communication-45",
      "videoFileName": "קזן 38 13 12 2012 אחרי הארוחה",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-16, profile-Carlos Kalman Szarfman, subscribers-28",
      "isCrop": ""
    },
    {
      "videoName": "כך נראתה הדרך לשטנד 2",
      "videoSubTitle": "ביום שישי אח איזה כיף זה היה",
      "videoDesc": "הגברים עושים לחיים למצלמה, הנשים אומרות ברכות לצלם על הזוגיות שלו. שני הצעירים שיושבים לצידה של הסבתא מורים לה מה לעשות.",
      "menAndWomen": "הגבר בראש השולחן אומר לאמו מה לעשות מול המצלמה ופונה אליה. הנשים פחות מורגשות באווירה.",
      "childrenAndParents": "מברכים את הצלם הצעיר על נישואיו ממקום שעברו זאת כבר ממזמן.",
      "year": 1992,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "bread-14, alcohol-14",
      "event": "other",
      "subjects": "photography-7, memory-21",
      "emotions": "happy-21, laugh-10",
      "objects": "tools-4, communication-1",
      "videoFileName": "כך נראתה הדרך לשטנד 2 ביום שישי אח איזה כיף זה היה",
      "isAutoPlay": "TRUE",
      "videoInformation": "desc-אין, views-60, profile-שבט חמציק ורבקה, subscribers-2",
      "isCrop": ""
    },
    {
      "videoName": "ערב שבועות אצל משפחת יהוד",
      "videoSubTitle": "בשוהם 2013",
      "videoDesc": "כולים יושבים בחדר ומדברים. שתי נשים מבקשות שהצלם יצלם אותן, אב המשפחה דורש שכולם יקומו לקידוש ומתבצע קידוש.",
      "menAndWomen": "הנשים בישלו. הגבר ראש המשפחה דורש קידוש וכולם מתייצבים.",
      "childrenAndParents": "הילדים עצמאיים ולא תלויים בהורים.",
      "year": 2013,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "alcohol-60, ashkenazi-9",
      "event": "holiday",
      "subjects": "text-25, photography-7",
      "emotions": "happy-13",
      "objects": "chairs-5",
      "videoFileName": "ערב שבועות אצל משפחת יהוד בשוהם 2013",
      "isAutoPlay": "",
      "videoInformation": "desc-עם משפחת אקווע, קלמן, אליהו, ושלמה, views-184, profile-Dani Yahud, subscribers-10",
      "isCrop": ""
    },
    {
      "videoName": "פותחים שולחן אצל שיבה הללי",
      "videoSubTitle": "עצמאות 2019",
      "videoDesc": "אישה עושה מוציא, מחלקת לכולם ומסבירה את הברכה. הצלמת מספרת על האוכל והאנשים ומבקשת שיצלמו גם אותה.",
      "menAndWomen": "אישה היא שעושה את הברכה על המוציא. גבר אחד נוכח סביב השולחן.",
      "childrenAndParents": "אין",
      "year": 2019,
      "lang": "hebrew, english",
      "relation": 3,
      "": "",
      "foodAndDrink": "alcohol-10, ashkenazi-27, bread-0",
      "event": "holiday",
      "subjects": "text-5, photography-31, food-24",
      "emotions": "laugh-37",
      "objects": "tools-7, communication-62",
      "videoFileName": "עצמאות  2019 - פותחים שולחן אצל שיבה הללי",
      "isAutoPlay": "",
      "videoInformation": "desc-ד' באייר תשע\"ט היה אחלה.., views-472, profile-מלכה טייכר מילר בנייד, subscribers-128",
      "isCrop": ""
    },
    {
      "videoName": "על האש אצל סבתא",
      "videoSubTitle": "",
      "videoDesc": "הסבתא מצלמת את הנכדים שלה ואז עובדת לצילום המבוגרים. מבקשת שיאחלו חג שמח למי שלכבודה עושים את הסרטון.",
      "menAndWomen": "יושבים במעורב.",
      "childrenAndParents": "הילדים הגדולים משחקים בצד ללא ההורים, התינוקת בידיים של אמא שלה.",
      "year": 2012,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "",
      "event": "bbq",
      "subjects": "memory-29, politiks-33, photography-23",
      "emotions": "happy-19, embarrassment-9",
      "objects": "chairs-27",
      "videoFileName": "על האש אצל סבתא",
      "isAutoPlay": "",
      "videoInformation": "desc-א, views-16, profile-Neomi Daee, subscribers-0",
      "isCrop": "FALSE"
    },
    {
      "videoName": "אחרי ארוחת חג",
      "videoSubTitle": "",
      "videoDesc": "הנשים מנקות ומארגנות את הבית והמטבח אחרי ארוחת החג. מוזיקה ברקע ורוקדים.",
      "menAndWomen": "הנשים מנקות, אחד הגברים עומד מהצד. השני מצלם ואחד הנשים מנענעת את פלג גופה העליון למצלמה.",
      "childrenAndParents": "הילדים מצטרפים לריקודים ולא עוזרים בסדר והנקיון.",
      "year": 2010,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "",
      "event": "holiday",
      "subjects": "",
      "emotions": "happy-8, laugh-20",
      "objects": "communication-1, chairs-6",
      "videoFileName": "אחרי ארוחת חג",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-17, profile-sarusi shabi, subscribers-0",
      "isCrop": "FALSE"
    },
    {
      "videoName": "על האש אצל דדי ואירית",
      "videoSubTitle": "חול המועד פסח",
      "videoDesc": "הצלם מספר על איכות המצלמה ונפרד מהסובבים מרחוק לפני שהולך. במקביל הסבתא שרה עם הנכדה שלה.",
      "menAndWomen": "יושבים במעורב.",
      "childrenAndParents": "ההורים משאירים את הילדה אצל סבתא ונפרדים ממנה לשלום.",
      "year": 2014,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "dessert-60",
      "event": "bbq",
      "subjects": "photography-0, memory-17",
      "emotions": "happy-39",
      "objects": "light-26, communication-20, art-44",
      "videoFileName": "על האש אצל דדי ואירית חול המועד פסח",
      "isAutoPlay": "",
      "videoInformation": "desc-בס\"ד סוף יום כיפי אצל דדי ואירית בנחלת, views-37, profile-avraham mualem, subscribers-27",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב בבית משפחת ורונה",
      "videoSubTitle": "",
      "videoDesc": "הילדים הצעירים שרים שיר תוך כדי אכילת ארוחת הערב. הילד הבוגר יותר צוחק עליהם ומובך. לאחר מכן גם ההורים צוחקים.",
      "menAndWomen": "אין",
      "childrenAndParents": "ההורים מצלמים ונותנים מקום לילדים שלהם וצוחקים מהם.",
      "year": 2013,
      "lang": "hebrew",
      "relation": 3,
      "": "",
      "foodAndDrink": "ashkenazi-18",
      "event": "other",
      "subjects": "memory-0",
      "emotions": "happy-2, laugh-20",
      "objects": "tools-14",
      "videoFileName": "ארוחת ערב בבית משפחת ורונה",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-469, profile-avigdo, subscribers-3",
      "isCrop": ""
    },
    {
      "videoName": "מפגש על האש אצל דרדלונה",
      "videoSubTitle": "",
      "videoDesc": "הצלם מצלם את כל האנשים, פונה לחלקם באופן אישי ומנסה לקבל את תגובתם.",
      "menAndWomen": "יושבים מעורב.",
      "childrenAndParents": "הילדים יושבים ליד ההורים אך מתנהלים בצורה עצמאית.",
      "year": 2009,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "",
      "event": "bbq",
      "subjects": "",
      "emotions": "happy-17, laugh-25, embarrassment-41",
      "objects": "chairs-84",
      "videoFileName": "מפגש על האש אצל דרדלונה",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-28, profile-liam7362, subscribers-140",
      "isCrop": ""
    },
    {
      "videoName": "משפחת שאול",
      "videoSubTitle": "פסח 2021 מנגל אצל סימה",
      "videoDesc": "רוב האנשים יושבים לשולחן ומדברים ביניהם. מגיעים אנשים נוספים ואומרים שלום, כולם מתייחסים לכניסה שלהם.",
      "menAndWomen": "גבר אחד עושה מתפעל את המנגל ומביא אוכל לשולחן. כל שאר האנשים יושבים לשולחן לאכול.",
      "childrenAndParents": "הורים וילדים יושבים בנפרד, האנשים שמצטרפים מגיעים כיחידה משפחתית של הורים וילדים.",
      "year": 2021,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "ashkenazi-10, mizrahi-5",
      "event": "bbq",
      "subjects": "food-1",
      "emotions": "happy-16, embarrassment-40",
      "objects": "tools-0",
      "videoFileName": "משפחת שאול פסח 2021 מנגל אצל סימה",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-42, profile-אלי שאולי, subscribers-604",
      "isCrop": ""
    },
    {
      "videoName": "מפגש אצל ליאור וארז אשכנזי (סימון)",
      "videoSubTitle": "יולי 2017",
      "videoDesc": "כל המבוגרים יושבים סביב השולחן ומדברים עם שני הזקנים על החוויות שלהם מהשואה.",
      "menAndWomen": "סביב השולחן יושבים בזוגות, גבר ואישה אחד ליד השניה.",
      "childrenAndParents": "המבוגרים מקשיבים לסיפורים של אבא שלהם. הילדים הצעירים יושבים בסלון ועסוקים בטלפונים.",
      "year": 2017,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "dessert-11",
      "event": "other",
      "subjects": "memory-0",
      "emotions": "",
      "objects": "light-26, communication-20",
      "videoFileName": "מפגש אצל ליאור וארז אשכנזי (סימון) יולי 2017",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-27, profile-ravid simon, subscribers-7",
      "isCrop": ""
    },
    {
      "videoName": "מסיבת העצמאות",
      "videoSubTitle": "אצל סבא ברוך וסבתא אסתרwmv",
      "videoDesc": "הצלם מצלם את כל האנשים ומנסה שידברו למצלמה, והם מתלוננים על הצילום. הוא צוחק על הילדים והם מבקשים ממנו ללכת.",
      "menAndWomen": "גבר מטפל במנגל, הצלם שואל את הנשים המבוגרות בנוגע לאוכל.",
      "childrenAndParents": "כל משפחה גרעינית יושבת בנפרד, הורים וילדים יחד.",
      "year": 2009,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "mizrahi-35, ashkenazi-39",
      "event": "holiday",
      "subjects": "food-0",
      "emotions": "anger-59",
      "objects": "tools-21",
      "videoFileName": "מסיבת העצמאות אצל סבא ברוך וסבתא אסתרwmv",
      "isAutoPlay": "",
      "videoInformation": "desc-בסרטון ילדים, נכדים, חתנים וכלות, views-136, profile-Moshe Yosef, subscribers-93",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב אצל סבאסבתא",
      "videoSubTitle": "",
      "videoDesc": "סבא מאכיל את הנכדה שלו. הוא ואמא שלה מדברים עליה ואיתה על האוכל. הילדה מבקשת עוד אוכל לבקשתה של אמא שלה והסבא שוב מאכיל אותה.",
      "menAndWomen": "האישה מצלמת והגבר מאכיל את הילדה.",
      "childrenAndParents": "האם מצלמת את הילדה, מתלהבת ממנה ומדברת איתה.",
      "year": 2014,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-4",
      "event": "other",
      "subjects": "food-1, politiks-10",
      "emotions": "happy-35, laugh-31, calm-12, embarrassment-34",
      "objects": "",
      "videoFileName": "ארוחת ערב אצל סבאסבתא",
      "isAutoPlay": "",
      "videoInformation": "desc-קדי בת שנה וחצי, views-44, profile-Einat Grossman, subscribers-28",
      "isCrop": ""
    },
    {
      "videoName": "ליל הסדר כל האחים לבית משפחת כהן",
      "videoSubTitle": "אצל שושי ומוטי 1990",
      "videoDesc": "כולם מתארגנים להתחלת הסדר ומדברים על מקומות הישיבה. יש הרבה רעש גם כשכולם כבר התיישבו.",
      "menAndWomen": "גבר יושב באחד מראשי השולחן, בשאר הישיבה מעורבת",
      "childrenAndParents": "רוב הילדים יושבים ליד ההורים שלהם.",
      "year": 1990,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "alcohol-23",
      "event": "holiday",
      "subjects": "",
      "emotions": "embarrassment-103",
      "objects": "chairs-14, art-0",
      "videoFileName": "ליל הסדר כל האחים לבית משפחת כהן אצל שושי ומוטי  1990",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-183, profile-dvora cohen, subscribers-2",
      "isCrop": ""
    },
    {
      "videoName": "ביום העצמאות על האש",
      "videoSubTitle": "חלק א' 16.4.13",
      "videoDesc": "אחד הגברים מתעסק עם המנגל וכולם מסביב אומרים שלום ומנהלים שיחות שונות.",
      "menAndWomen": "גבר מתפעל את המנגל, הנשים עומדות בחוץ ליד ומדברות.",
      "childrenAndParents": "הילדה הקטנה על הידיים של אמא שלה. הילדים האחרים מסתובבים.",
      "year": 2013,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-8, mizrahi-3",
      "event": "holiday",
      "subjects": "memory-55, food-43, politiks-12",
      "emotions": "happy-18, embarrassment-64",
      "objects": "chairs-0",
      "videoFileName": "ביום העצמאות על האש חלק א'  16.4.13",
      "isAutoPlay": "",
      "videoInformation": "desc-עם הפלורנטינים על האש בחג העצמאות אצל סבתא מזל, views-79, profile-אריה בן-אברהם, subscribers-58",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת צהריים אצל מש' זכאי הצעירה",
      "videoSubTitle": "דצמבר 2014",
      "videoDesc": "הצלם מבקש הסברים מהמארחים על מה שהם מכינים ועל מי שהולך להגיע.",
      "menAndWomen": "הגבר והאישה שניהם מבשלים את הארוחה.",
      "childrenAndParents": "שומעים ילדים ברקע אבל ההורים לא איתם.",
      "year": 2014,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "mizrahi-23, ashkenazi-0",
      "event": "other",
      "subjects": "food-20",
      "emotions": "laugh-38",
      "objects": "chairs-16",
      "videoFileName": "ארוחת צהריים אצל מש' זכאי  דצמבר 2014 הצעירה",
      "isAutoPlay": "",
      "videoInformation": "desc-דצמבר 2014, views-41, profile-אייל אורי זכאי, subscribers-29",
      "isCrop": "FALSE"
    },
    {
      "videoName": "ארוחת שישי אצל קובה",
      "videoSubTitle": "מסרט1",
      "videoDesc": "כולם יושבים ומנהלים שיחות שונות תוך כדי האוכל.",
      "menAndWomen": "כמה גברים על המנגל, שאר האנשים יושבים לאכול.",
      "childrenAndParents": "הילדה נמצאת ליד אמא שלה.",
      "year": 1994,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "mizrahi-1, alcohol-46",
      "event": "friday",
      "subjects": "memory-8, food-154",
      "emotions": "happy-15, laugh-43",
      "objects": "chairs-5",
      "videoFileName": "ארוחת שישי אצל קובה מסרט1",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-10, profile-יוגב צפריר, subscribers-11",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת צהרים אצל משפחת ערמוני",
      "videoSubTitle": "",
      "videoDesc": "אנשים יושבים סביב השולחן לקראת סוף הארוחה, יש ויכוח בין הגברים. מרוקנים לאט לאט את השולחן אחרי האוכל.",
      "menAndWomen": "הגברים מתווכחים סביב השולחן, חלק מהנשים דואגות לפינוי השולחן והטיפול בילדים.",
      "childrenAndParents": "הילדים כבר לא ליד השולחן. ישנה תינוקת אחת על הידיים של אמא שלה.",
      "year": 2017,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "",
      "event": "other",
      "subjects": "",
      "emotions": "anger-15",
      "objects": "light-0, chairs-107, tools-8, art-2",
      "videoFileName": "ארוחת צהרים אצל משפחת ערמוני",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-22, profile-Erez Armoni, subscribers-0",
      "isCrop": ""
    },
    {
      "videoName": "איזה זמרים אחים שלי",
      "videoSubTitle": "",
      "videoDesc": "כולם מגיבים למצלמה. לאחר מכן ממשיכים בקריוקי.",
      "menAndWomen": "יש רוב גברי אך גם הנשים משתתפות בשירה.",
      "childrenAndParents": "אין יחסים ברורים",
      "year": 2012,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-35, ashkenazi-26",
      "event": "other",
      "subjects": "politiks-20, photography-6",
      "emotions": "laugh-63, anger-3",
      "objects": "chairs-87, tools-28",
      "videoFileName": "איזה זמרים אחים שלי",
      "isAutoPlay": "",
      "videoInformation": "desc-על האש אצל יניב, views-33, profile-\nדוד אבוטבול אילוף כלבים, subscribers-4",
      "isCrop": ""
    },
    {
      "videoName": "על האש אצל אביבה",
      "videoSubTitle": "",
      "videoDesc": "אנשים סביב השולחן לוקחים אוכל לצלחות ומתחמקים מהמצלמה.",
      "menAndWomen": "גברים מתפעלים את המנגל, הנשים סביב השולחן.",
      "childrenAndParents": "הילדים עצמאיים, אין קשר ישיר להורים.",
      "year": 2010,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "mizrahi-2, ashkenazi-17, bread-38",
      "event": "bbq",
      "subjects": "food-4",
      "emotions": "embarrassment-7",
      "objects": "chairs-15",
      "videoFileName": "על האש אצל אביבה",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-25, profile-Sharon Eisenman, subscribers-1",
      "isCrop": ""
    },
    {
      "videoName": "אילן ומעיין בשיחת ארוחת ערב",
      "videoSubTitle": "",
      "videoDesc": "כולם יושבים לשולחן, שני הילדים הקטנים מנהלים שיחה ביניהם והסובבים קשובים להם. חלק מתייחסים למצלמה.",
      "menAndWomen": "אין",
      "childrenAndParents": "אבא של הילדה מצלם אותה בשיחה עם ילד נוסף, נראה כי יש ביניהם יחסים טובים. הילדה הגדולה שלו מתלוננת על זה שהוא מצלם אותה גם והאמא מרגיעה אותה.",
      "year": 2019,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "bread-16, ashkenazi-14",
      "event": "other",
      "subjects": "memory-23, photography-4",
      "emotions": "embarrassment-11, anger-20",
      "objects": "tools-0",
      "videoFileName": "אילן ומעיין בשיחת ארוחת ערב",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-28, profile-יובל ניומן, subscribers-53",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב טיפוסית.",
      "videoSubTitle": "",
      "videoDesc": "רעש של ילדים מסביב, צועקים. אחד הילדים שר ורוצה שיצלמו אותו. הילדה בכיסא תינוק מצטרפת אליו. שניהם רוצים את תשומת הלב.",
      "menAndWomen": "אין",
      "childrenAndParents": "ניתן להניח שהאבא מצלם את הילדים. הוא לא יוצר איתם אינטראקציה מעבר.",
      "year": 2007,
      "lang": "hebrew",
      "relation": 3,
      "": "",
      "foodAndDrink": "",
      "event": "other",
      "subjects": "memory-5",
      "emotions": "happy-16, anger-0",
      "objects": "chairs-57, tools-2",
      "videoFileName": "ארוחת ערב  .טיפוסית",
      "isAutoPlay": "",
      "videoInformation": "desc-שירים, views-278, profile-nira6, subscribers-5",
      "isCrop": ""
    },
    {
      "videoName": "על האש בשדמה",
      "videoSubTitle": "עם תמי ועמי 2016",
      "videoDesc": "אנשים רוקדים במטבח בזוגות לצלילי מוזיקה בספרדית.",
      "menAndWomen": "רוקדים בזוגות גברים ונשים. שתי הנשים הנוספות לא רוקדות ביחד.",
      "childrenAndParents": "נראה כי אחד הגברים רוקד עם בתו הבוגרת.",
      "year": 2016,
      "lang": "espanol",
      "relation": 2,
      "": "",
      "foodAndDrink": "bread-2",
      "event": "bbq",
      "subjects": "",
      "emotions": "laugh-4",
      "objects": "light-16, chairs-9",
      "videoFileName": "על האש בשדמה עם תמי ועמי 2016",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-38, profile-Jackie Tramer, subscribers-25",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב אצל שמרית",
      "videoSubTitle": "",
      "videoDesc": "מתפעלים מהמארחים ומהשולחן. הצלם מכיר לצופים את הנפשות הפועלות. האישה המבוגרת מודה לצלם על ההשקעה שלהם.",
      "menAndWomen": "הצלם מספר כי אחת הנשים היא האחראית על הבישולים, בעלה מביא כיסאות.",
      "childrenAndParents": "הילדים הקטנים על הידיים של המבוגרים.",
      "year": 2014,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-11, ashkenazi-8",
      "event": "other",
      "subjects": "",
      "emotions": "happy-2",
      "objects": "chairs-6",
      "videoFileName": "ארוחת ערב אצל שמרית",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-14, profile-David Mesika, subscribers-48",
      "isCrop": ""
    },
    {
      "videoName": "על האש אצל הוריי",
      "videoSubTitle": "פסח 2018",
      "videoDesc": "רוב האנשים עסוקים באכילה. מתקיימת שיחה רחוקה ביi מבוגרים ושיחה קרובה בין אבא לבת.",
      "menAndWomen": "2 גברים על המנגל, כל הנשים יושבות לשולחן.",
      "childrenAndParents": "האבא מדבר עם הבת שלו שיושבת לידו ומסביר לה דברים בסבלנות.",
      "year": 2018,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "alcohol-5, mizrahi-10",
      "event": "holiday",
      "subjects": "",
      "emotions": "calm-0",
      "objects": "light-2, tools-8",
      "videoFileName": "פסח 2018 על האש אצל הוריי",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-23, profile-Amalia Kiral, subscribers-2",
      "isCrop": ""
    },
    {
      "videoName": "קידוש וארוחת ערב ליל שבת",
      "videoSubTitle": "בבית משפחת כהן באשקלון",
      "videoDesc": "אב המשפחה מקדש ועושה מוציא, תוך כדי האמא שמה אוכל בצלחות. האמא מתגאה בלחם שלה. הרבה רעש מצד הילדים.",
      "menAndWomen": "גבר עושה קידוש ומוציא, האמא מחלקת אוכל לכולם.",
      "childrenAndParents": "הילדים מרעישים וההורים כועסים עליהם. ילדים יושבים בראש השולחן.",
      "year": 2011,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-13, ashkenazi-42, bread-45",
      "event": "friday",
      "subjects": "food-30, text-0",
      "emotions": "happy-26, laugh-65, anger-79",
      "objects": "tools-21",
      "videoFileName": "קידוש וארוחת ערב ליל שבת בבית משפחת כהן באשקלון",
      "isAutoPlay": "TRUE",
      "videoInformation": "desc-דני מקדש את השבת.., views-750, profile-Ofer Hen, subscribers-18",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב יום העצמאות",
      "videoSubTitle": "",
      "videoDesc": "הצלם מדבר למצלמה. הוא מתאר את האוכל והאירוע.",
      "menAndWomen": "אין",
      "childrenAndParents": "הילדים גדולים, יושבים בנפרד מההורים",
      "year": 2020,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "mizrahi-5, alcohol-0, bread-13",
      "event": "friday",
      "subjects": "food-4",
      "emotions": "happy-2",
      "objects": "tools-8",
      "videoFileName": "ארוחת ערב יום העצמאות",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-19, profile-David Avramov, subscribers-49",
      "isCrop": ""
    },
    {
      "videoName": "יום הולדת 31 לעודד",
      "videoSubTitle": "",
      "videoDesc": "הגבר המבוגר עושה חלק מברכות החג. הצלמת מצלמת את סובבי השולחן ורק האחרון מתייחס למצלמה.",
      "menAndWomen": "הגברים יושבים בראש השולחן, אחד מהם עושה את הברכה והנשים מסביב.",
      "childrenAndParents": "אמא יושבת ליד הבן שלה.",
      "year": 2010,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "alcohol-2, ashkenazi-12",
      "event": "bday",
      "subjects": "text-0",
      "emotions": "calm-8, laugh-15",
      "objects": "",
      "videoFileName": "יום הולדת 31 לעודד",
      "isAutoPlay": "",
      "videoInformation": "desc-אין, views-119, profile-Adi Lailiav, subscribers-7",
      "isCrop": ""
    },
    {
      "videoName": "ערב חג פסח אצל משפחתי היקרה",
      "videoSubTitle": "29 03 2010 משפחת חרבי יונית עוזרי",
      "videoDesc": "חלק מהאנשים סביב השולחן שרים חלק ממהגדה ומתבדרים מזה. אחד השרים מניף בקבוק תירוש ריק באוויר, אחרים מוחאים כפיים.",
      "menAndWomen": "גבר יושב לראש השולחן, שאר הגברים יושבים בצד אחד שלו והנשים בצד השני.",
      "childrenAndParents": "אין",
      "year": 2010,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "alcohol-4, ashkenazi-10",
      "event": "holiday",
      "subjects": "text-0",
      "emotions": "laugh-8",
      "objects": "",
      "videoFileName": "ערב חג פסח 29 03 2010 אצל משפחתי היקרה משפחת חרבי יונית עוזרי 023",
      "isAutoPlay": "TRUE",
      "videoInformation": "desc-אין, views-84, profile-יונית עוזרי, subscribers-8.36K",
      "isCrop": ""
    },
    {
      "videoName": "חוגגים יום הולדת 3 לאיתי",
      "videoSubTitle": "",
      "videoDesc": "חוגגים יום הולדת לילד ושרים לו \"היום יום הולדת\". מרימים אותו על כסא.",
      "menAndWomen": "משתתפים באופן שווה בחגיגה",
      "childrenAndParents": "אמא של הילד מנשקת אותו והוא יושב עליה. האבא מציע לו שירימו אותו ושני ההורים מרימים אותו על הכיסא בהתרגשות.",
      "year": 2012,
      "lang": "hebrew",
      "relation": 2,
      "": "",
      "foodAndDrink": "dessert-2",
      "event": "bday",
      "subjects": "memory-6",
      "emotions": "happy-0",
      "objects": "chairs-32, tools-80",
      "videoFileName": "חוגגים  יום הולדת 3  לאיתי",
      "isAutoPlay": "",
      "videoInformation": "desc-עוגת יום הולדת עם פו וטיגר מתנות ויאללה בלאגן, views-395, profile-moshe shalev, subscribers-16",
      "isCrop": ""
    },
    {
      "videoName": "ארוחת ערב יום שישי",
      "videoSubTitle": "אצל בל עם האורחים מאמריקה",
      "videoDesc": "הצלם מספר על האירוע. כולם נמצאים בסלון, המארחת מזמינה את כולם לשבת.",
      "menAndWomen": "חלק מהנשים עומדות במטבח ועוזרות למארחת בהכנות. הגברים ברובם בסלון.",
      "childrenAndParents": "הילדים הקטנים משחקים בחוץ ללא קשר להורים, הנערה נמצאת עם הנשים במטבח.",
      "year": 2019,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "ashkenazi-12",
      "event": "friday",
      "subjects": "",
      "emotions": "",
      "objects": "tools-11, communication-5 art-1",
      "videoFileName": "ארוחת ערב יום שישי אצל בל עם האורחים מאמריקה",
      "isAutoPlay": "",
      "videoInformation": "desc-צולם ע\"י דוד אברמוב כל הזכויות שמורות, views-4, profile-David Avramov, subscribers-49",
      "isCrop": ""
    },
    {
      "videoName": "אצל מורדי בחצר",
      "videoSubTitle": "",
      "videoDesc": "האנשים עושים ישיבה בחוץ, מי שמבחין במצלמה מגיב אליה. מתחילים להתארגן לקריוקי, בזמן שאחד הגברים עושה מנגל.",
      "menAndWomen": "הגברים מנהלים את העניינים והנשים לא מתערבות.",
      "childrenAndParents": "הילדים גדולים, אין יחס ברור בינם לבין הוריהם.",
      "year": 2014,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "alcohol-42, mizrahi-46",
      "event": "bbq",
      "subjects": "",
      "emotions": "happy-7, laugh-27",
      "objects": "chairs-0, tools-45",
      "videoFileName": "אצל מורדי בחצר",
      "isAutoPlay": "",
      "videoInformation": "desc-על האש אצל מורדי אחי, views-52, profile-יוסי שיפרוט, subscribers-17",
      "isCrop": ""
    },
    {
      "videoName": "חג עצמאות",
      "videoSubTitle": "2019 אצל מני בראש פינה",
      "videoDesc": "האנשים יושבים מסביב לשולחן ואוכלים. אחד הגברים מטפל במנגל. יש מוזיקה ברקע והצלמת מברכת את כולם בחג שמח.",
      "menAndWomen": "חלק מהגברים מטפלים בבשר, כמה נשים מביאות עוד אוכל מתוך הבית. השאר יושבים לשולחן.",
      "childrenAndParents": "הילדים יושבים ליד ההורים שלהם. אחת הילדות עוזרת לאבא שלה שמטפל במנגל.",
      "year": 2019,
      "lang": "hebrew",
      "relation": 1,
      "": "",
      "foodAndDrink": "mizrahi-19, ashkenazi-76",
      "event": "holiday",
      "subjects": "memory-14",
      "emotions": "happy-32, laugh-48",
      "objects": "chairs-61, tools-59",
      "videoFileName": "חג עצמאות 2019 אצל מני בראש פינה",
      "isAutoPlay": "",
      "videoInformation": "desc-על האש, views-24, profile-דובי מאזוז, subscribers-11",
      "isCrop": ""
    }
]

// REMOVE when PROD
// const videosStubData = [videos[0], videos[1], videos[2], videos[3], videos[4]]
const videosStubData = videos

export default videosStubData
